# Generated by Django 2.1.7 on 2020-04-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceevent',
            name='link_chat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Линк на чат'),
        ),
        migrations.AddField(
            model_name='diceevent',
            name='title_chat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя чата'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата event-a'),
        ),
    ]
