# Generated by Django 2.1.7 on 2020-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='name',
            field=models.CharField(default='Сообщение без номера', max_length=30, verbose_name='Название сообщения'),
        ),
    ]
