# Generated by Django 2.1.7 on 2020-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200403_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceevent',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
