# Generated by Django 2.1.7 on 2020-04-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200403_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unbond',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='unbond',
            name='user',
        ),
        migrations.DeleteModel(
            name='Unbond',
        ),
    ]
