# Generated by Django 2.1.7 on 2020-04-05 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200405_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diceevent',
            name='summa',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24, verbose_name='Cумма выигрыша'),
        ),
    ]
