# Generated by Django 2.1.7 on 2020-04-06 14:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200405_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=85, verbose_name='Номер кошелька')),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24, verbose_name='сумма на выплату')),
                ('coin', models.CharField(default='-', max_length=10, verbose_name='Монета,в к-ой идет выплата')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Прислано уведомление об оплате')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платеж',
            },
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Отправлено на выплату?'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.DiceEvent', verbose_name='Бросок кубика'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Пользователь ТГ'),
        ),
    ]
