# Generated by Django 2.1.7 on 2020-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200406_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceevent',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Отправлено на выплату?'),
        ),
    ]
