# Generated by Django 2.1.7 on 2020-04-07 12:48

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_diceevent_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='user',
            name='today_state',
            field=users.fields.JSONField(default=dict, verbose_name='Состояние юзера сегодня'),
        ),
    ]
