# Generated by Django 2.1.7 on 2020-04-12 18:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_allowedchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedchat',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='minterwallets',
            name='number',
        ),
        migrations.AddField(
            model_name='allowedchat',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='allowedchat',
            name='status',
            field=models.CharField(choices=[('errored', 'Ошибка определения даты создания'), ('restricted', 'Чат запрещен'), ('activated', 'Чат разрешен')], default=None, max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='allowedchat',
            name='status_updated_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата последнего обновления статуса'),
        ),
        migrations.AddField(
            model_name='minterwallets',
            name='address',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Адрес (Mx...)'),
        ),
        migrations.AddField(
            model_name='minterwallets',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='minterwallets',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления баланса'),
        ),
        migrations.AlterField(
            model_name='allowedchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата появления в БД'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='chat_id',
            field=models.BigIntegerField(default=1, verbose_name='Id-чата совершенного event-a'),
        ),
        migrations.AlterField(
            model_name='minterwallets',
            name='mnemonic',
            field=models.TextField(verbose_name='Сид фраза'),
        ),
    ]
