# Generated by Django 2.1.7 on 2020-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200412_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minterwallets',
            name='address',
            field=models.CharField(default='', max_length=85, verbose_name='Адрес (Mx...)'),
            preserve_default=False,
        ),
    ]
