# Generated by Django 2.1.7 on 2020-04-13 14:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200412_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedchat',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='diceevent',
            options={'verbose_name': 'Бросок кубика', 'verbose_name_plural': 'Броски кубика'},
        ),
        migrations.AlterModelOptions(
            name='exceptions',
            options={'verbose_name': 'Blacklist', 'verbose_name_plural': 'Blacklist'},
        ),
        migrations.AlterModelOptions(
            name='minterwallets',
            options={'verbose_name': 'Minter-Кошелек', 'verbose_name_plural': 'Minter-Кошельки'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
        migrations.AlterModelOptions(
            name='triggers',
            options={'verbose_name': 'Триггер', 'verbose_name_plural': 'Триггеры'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='tools',
            name='join',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='ms',
        ),
        migrations.AddField(
            model_name='tools',
            name='address',
            field=models.CharField(default='', max_length=42, verbose_name='Адрес выплат'),
        ),
        migrations.AddField(
            model_name='tools',
            name='mnemonic',
            field=encrypted_model_fields.fields.EncryptedTextField(default='', verbose_name='Seed-фраза'),
        ),
        migrations.AlterField(
            model_name='allowedchat',
            name='link_chat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Юзернейм группы'),
        ),
        migrations.AlterField(
            model_name='allowedchat',
            name='status',
            field=models.CharField(choices=[('errored', 'Ошибка определения даты создания'), ('restricted', 'Группа запрещена'), ('activated', 'Группа разрешена')], default=None, max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='chat_id',
            field=models.BigIntegerField(default=1, verbose_name='Chat ID совершенного event-a'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Прислано уведомление об оплате'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Отправлено на выплату'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='is_win',
            field=models.BooleanField(default=False, verbose_name='Победа'),
        ),
        migrations.AlterField(
            model_name='diceevent',
            name='link_chat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Юзернейм чата'),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='minterwallets',
            name='address',
            field=models.CharField(max_length=42, verbose_name='Адрес (Mx...)'),
        ),
        migrations.AlterField(
            model_name='minterwallets',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление баланса'),
        ),
        migrations.AlterField(
            model_name='minterwallets',
            name='mnemonic',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Сид фраза'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24, verbose_name='Сумма на выплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='payload',
            field=models.CharField(default='', max_length=80, verbose_name='Payload при выводе средств из бота'),
        ),
    ]
