# Generated by Django 2.1.7 on 2020-04-14 00:46
from datetime import datetime

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200413_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedchat',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.utcnow, verbose_name='Дата появления в БД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowedchat',
            name='created_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата создания чата'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='mnemonic',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Seed-фраза'),
        ),
    ]
