# Generated by Django 2.1.7 on 2020-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200414_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Отрицательные отклики'),
        ),
        migrations.AddField(
            model_name='user',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество полученных reply'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Положительные отклики'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='chat_limit_day',
            field=models.DecimalField(decimal_places=6, default=200, max_digits=24, verbose_name='Лимит таймов на чат, в день'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='coin',
            field=models.CharField(default='TIME', max_length=10, verbose_name='Монета,в к-ой идет выплата'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='total_limit_day',
            field=models.DecimalField(decimal_places=6, default=4000, max_digits=24, verbose_name='Общий лимит таймов на всех, в день'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='user_limit_day',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=24, verbose_name='Лимит таймов на одного юзера, в день'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата появления в боте'),
        ),
    ]
