# Generated by Django 2.1.7 on 2020-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200414_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggers',
            name='name',
        ),
        migrations.AddField(
            model_name='triggers',
            name='action',
            field=models.CharField(choices=[('upvote', 'Повысить репутацию'), ('downvote', 'Понизить репутацию'), ('dice', 'Бросить кость')], default='dice', max_length=20, verbose_name='Действие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triggers',
            name='exact',
            field=models.BooleanField(default=False, verbose_name='Требует точного совпадения'),
        ),
        migrations.AddField(
            model_name='triggers',
            name='phrase',
            field=models.CharField(default='dice time', max_length=30, verbose_name='Ключевая фраза'),
            preserve_default=False,
        ),
    ]
