# Generated by Django 2.2.12 on 2020-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200415_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_updates_skip_until', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
