# Generated by Django 2.2.12 on 2020-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedchat',
            name='coin',
            field=models.CharField(default='TIME', max_length=10, verbose_name='Монета чата'),
        ),
    ]
