# Generated by Django 2.2.12 on 2020-04-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_allowedchat_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceevent',
            name='coin',
            field=models.CharField(default='TIME', max_length=10, verbose_name='Монета выигрыша'),
        ),
        migrations.AddField(
            model_name='diceevent',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='Локальный выигрыш'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_local',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ChatWallet'),
        ),
    ]
