# Generated by Django 2.2.12 on 2020-04-25 06:57

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200418_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatwallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='minterwallets',
            name='balance',
        ),
        migrations.AddField(
            model_name='chatwallet',
            name='balances',
            field=users.fields.JSONField(default=dict, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='minterwallets',
            name='balances',
            field=users.fields.JSONField(default=dict, verbose_name='Баланс'),
        ),
    ]
