# Generated by Django 2.2.12 on 2020-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200514_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diceevent',
            name='title_chat',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Имя чата'),
        ),
    ]
