# Generated by Django 2.2.12 on 2020-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200514_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedchat',
            name='link_chat',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Юзернейм группы'),
        ),
        migrations.AlterField(
            model_name='allowedchat',
            name='title_chat',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Имя чата'),
        ),
    ]
