# Generated by Django 2.2.12 on 2020-05-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200514_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minterwallets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.User', verbose_name='Владелец кошелька'),
        ),
        migrations.CreateModel(
            name='ChatAirdrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('last', 'Среди последних написавших'), ('next', 'Среди следующих написавших')], max_length=10, verbose_name='Режим')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта')),
                ('message_id', models.BigIntegerField(null=True, verbose_name='ID сообщения в чате')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24, verbose_name='Cумма')),
                ('coin', models.CharField(default='TIME', max_length=10, verbose_name='Монета')),
                ('users_total', models.PositiveIntegerField(verbose_name='Макс. количество участников')),
                ('users_current', models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Отметка об окончании')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AllowedChat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Пользователь')),
            ],
        ),
    ]
