# Generated by Django 2.2.12 on 2020-05-26 16:13

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200517_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial',
            field=users.fields.JSONField(default=dict, verbose_name='Туториалы юзера'),
        ),
    ]
